// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:425035901575:web:0ec75fa8fc2aa3e4f8e622',
    messagingSenderId: '425035901575',
    projectId: 'turf-f1980',
    authDomain: 'turf-f1980.firebaseapp.com',
    storageBucket: 'turf-f1980.firebasestorage.app',
    measurementId: 'G-81YD4MY3TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7xQ71hb3ysGXrg5pnVq-KA4nL-SQNKjY',
    appId: '1:425035901575:android:6ebafca1fe55f4e1f8e622',
    messagingSenderId: '425035901575',
    projectId: 'turf-f1980',
    storageBucket: 'turf-f1980.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoHJUPPQR_mJxJ0vE3I1r4LVz88pWKvHE',
    appId: '1:425035901575:ios:fbc31c4bc8eda1aff8e622',
    messagingSenderId: '425035901575',
    projectId: 'turf-f1980',
    storageBucket: 'turf-f1980.firebasestorage.app',
    iosBundleId: 'com.example.snabbitTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoHJUPPQR_mJxJ0vE3I1r4LVz88pWKvHE',
    appId: '1:425035901575:ios:fbc31c4bc8eda1aff8e622',
    messagingSenderId: '425035901575',
    projectId: 'turf-f1980',
    storageBucket: 'turf-f1980.firebasestorage.app',
    iosBundleId: 'com.example.snabbitTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:425035901575:web:797a5625442b618ff8e622',
    messagingSenderId: '425035901575',
    projectId: 'turf-f1980',
    authDomain: 'turf-f1980.firebaseapp.com',
    storageBucket: 'turf-f1980.firebasestorage.app',
    measurementId: 'G-9QCF2NWQW4',
  );
}
